# Port the server listens on (default is 8080)
server.port=8080
spring.application.name=car-fuel-tracker
logging.level.root=INFO
logging.level.com.codehills.cartracker=DEBUG
spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=NON_NULL